### ISSUE TITLE
typescript?

### ISSUE THREAD

**Issue by johannordin** [cpx86/protoactor-js#2]
i think typescript is an awesome help when writing js, and even more so if you are writing a lib. would you interrested in a pr?

**Comment by cpx86** [comment]
Absolutely, as long as the resulting JS is friendly from pure JS code. At the moment I've only focused on NodeJS though, so it shouldn't be a problem. It supports 99% of ES2015 and ES2016, so probably the JS code will be nearly identical if we target ES2016.
